### ISSUE TITLE
uninitialized constant Hanami::Mailer::Configuration (NameError)

### ISSUE THREAD

**Issue by ksr-13** [hanami/mailer#132]
Hanami.app.register_provider :hanami_mailer do
  start do
   ```
 require 'hanami/mailer'

    configuration = Hanami::Mailer::Configuration.new do |config|
      config.root            = File.expand_path(__dir__, "base")
      config.delivery_method = :test
    end

    register "hanami_mailer", configuration
```
  end
end

When registering a provider or using the block of code (in the 'start' block above) from the examples directory as an initializer getting error: 

uninitialized constant Hanami::Mailer::Configuration (NameError)

    configuration = Hanami::Mailer::Configuration.new do |config|
                                  ^^^^^^^^^^^^^^^
                                  
Ruby: ruby 3.3.0preview2
Hanami: 2.0.3
OS: 14.0 (23A344)

**Comment by ksr-13** [comment]
When adding 'Hanami-mailer' to Gemfile and not specifying a version bundle install is defaulting to version 0.0.0. This seems to be the issue. Don't know if it should be doing that.

**Comment by jodosha** [comment]
@ksr-13 The problem is that we haven't release yet a 2.x version of Mailer.
Can you please try with the following line in your `Gemfile`?

```ruby
gem "hanami-mailer", github: "hanami/mailer", branch: "main"
```
