### ISSUE TITLE
Make compatible with mime-types 3.0

### ISSUE THREAD

**Issue by jodosha** [hanami/mailer#45]
`lotus-mailer` depends on `mail`.
Starting from `mail-2.6.8`, this gem will depend on `mime-types-3.0`, because this can save a few megabytes of memory for Ruby applications.

I've tried to run our test suite with `mail-2.6.8-rc2` (in our `Gemfile`), but this [test](https://github.com/lotus/mailer/blob/master/test/delivery_test.rb#L50) fails:

```shell
  1) Failure:
Lotus::Mailer::.deliver::test delivery with hardcoded values#test_0004_interprets the prepare statement [/Users/luca/Code/lotus/mailer/test/delivery_test.rb:60]:
--- expected
+++ actual
@@ -1 +1 @@
-"application/pdf; charset=UTF-8; filename=invoice.pdf"
+"application/pdf; filename=invoice.pdf"
```

I [reported](https://github.com/mikel/mail/pull/953#issuecomment-171573441) this problem and got a reply from @halostatue (maintainer of `mime-types`) [who explains the reason](https://github.com/mikel/mail/pull/953#issuecomment-171655466) of this failure.

---

We need to make sure that if our users will do a `bundle update` and use under the hood `mail-2.6.8`, won't be affected by any problem.

**Comment by joneslee85** [comment]
@jodosha I would like to claim this ticket for the weekend

**Comment by davydovanton** [comment]
@joneslee85 If you need a help I'm ready to help

**Comment by voanhduy1512** [comment]
I guess the main problem it because of this commit https://github.com/mikel/mail/commit/f19204dcfa8c58647abf9126998b1a27b04ded1e

**Comment by joneslee85** [comment]
@voanhduy1512 yes pls
