### ISSUE TITLE
Use other solution for preview emails in dev env

### ISSUE THREAD

**Issue by davydovanton** [hanami/mailer#61]
I think that mail previewing is very important part for developers. That's why I suggest to add [letter_opener][letter_opener] gem for this. Integration with this gem is very simple and I hope that it'll be helpful for others developers too.

What do you think?

/cc @hanami/contributors and @hanami/core-team 

[letter_opener]: https://github.com/ryanb/letter_opener

**Comment by gotjosh** [comment]
I think this is a great approach! Do you mind if I take a stab at it?

**Comment by davydovanton** [comment]
@gotjosh yes, if you want I have a [blog post](http://blog.davydovanton.com/2016/05/21/preview-hanami-emails-in-browser/) about this. I think it will be helpful 😄

**Comment by cllns** [comment]
@davydovanton I like `letter_opener`. Are you suggesting adding `letter_opener` as a development dependency on `hanami-mailer`, or adding a note about `letter_opener` in the docs?

**Comment by davydovanton** [comment]
@cllns, I suggest add this gem as a dependency. But I think note will be good too.

**Comment by gotjosh** [comment]
I assummed it refers to adding it as a development depency as well.

**Comment by jodosha** [comment]
@davydovanton Do you mean to add as a dependency to a new Hanami project (eg. `hanami new`)?

**Comment by davydovanton** [comment]
@jodosha  I suggest one of ways:
1. Add dependency to new hanami project (only for development environment)
2. Add note to guides about preview emails

And of course I understand that new dependency isn't always good. That's why I suggest two ways.

**Comment by hlegius** [comment]
My two cents: I'd go with the second option - a note into Hanami guides.
IMO, not everyone will use it (APIs, other 3rd-party email services like Mandrill, etc).

**Comment by jodosha** [comment]
I agree with @hlegius.

We can:

  1. Add it to the guides.
  2. Add as **commented gem** in `Gemfile`.

@davydovanton Do you want to prepare these two PRs? Thanks.

**Comment by davydovanton** [comment]
@jodosha yes, of course

**Comment by jdickey** [comment]
What ever became of this? I don't see anything in the Hanami 1.3.1. docs for Mailers, nor does the current mailer repo have any other [reference](https://github.com/hanami/mailer/search?q=letter_opener) to `letter_opener` than this issue. I found Anton's [_Preview hanami emails in browser_](https://www.davydovanton.com/2016/05/21/preview-hanami-emails-in-browser/) blog post (the link in the earlier comment no longer works) and it sounds useful, but it also sounds as though it's missing a step that's touched on here.

Thanks.

**Comment by davydovanton** [comment]
@jdickey hey, thanks for ping. let's make it real 👍
