### ISSUE TITLE
Shouldn't mailer belong to a specific application?

### ISSUE THREAD

**Issue by BenBach** [hanami/mailer#71]
Hi I was wondering about the following:
Shouldn't a mailer belong to a specific application. An admin app might send different emails than the regular web interface.

Maybe I am understanding it all wrong, but for mailing is another way of serving content like rendering an html page is

**Comment by davydovanton** [comment]
Hey, we have it:
https://github.com/hanami/hanami/issues/648

That's why I'll close this issue
Thank you 👍
